"""
Django settings for pagelabproject.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

## BASE_DIR is where your manage.py is.
## SETTINGS_PATH is BASE_DIR + your_project_name (where settings.py is).
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))


DATA_UPLOAD_MAX_MEMORY_SIZE = 36214400
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qhk(v0g!4#(+_$$36hyks$nx!wkq$g&8qfgb92)92e)jkm1g%a'

# SECURITY WARNING: don't run with debug turned on in production!
# To test Django in "debug = false" mode, but using Django to server static files as in dev, 
#  run this locally:  `manage.py runserver --insecure`
DEBUG = os.getenv('DJANGO_DEBUG_FLAG', False)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

if os.getenv('DJANGO_ALLOWED_HOST'): 
    ALLOWED_HOSTS.append(os.getenv('DJANGO_ALLOWED_HOST'))
    
INTERNAL_IPS = ['127.0.0.1',]

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {
    'location': os.getenv('DJANGO_PAGELAB_DBBACKUP_PATH', '')
}
DBBACKUP_DATE_FORMAT = 'date-%d-%H'
DBBACKUP_FILENAME_TEMPLATE = 'pagelab-{datetime}.{extension}'


FORCE_SCRIPT_NAME = os.getenv('DJANGO_FORCE_SCRIPT_NAME', '/pagelab')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.sites',
    'report',
    'dbbackup',
    'compressor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append(
        'debug_toolbar.middleware.DebugToolbarMiddleware')
    INSTALLED_APPS.append('debug_toolbar')

ROOT_URLCONF = 'pageaudit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(SETTINGS_PATH, '../templates'),
            'templates',
            'report/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pageaudit.wsgi.application'


## Admins get 500 errors
## Managers get 404 errors
ADMINS = []
MANAGERS = []
ADMINS_EMAIL_TO_SMS = []


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', 
        'NAME': os.getenv('DJANGO_DB_NAME', 'perf_lab'),
        'USER': os.getenv('DJANGO_DB_USER', 'perf_lab'),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.getenv('DJANGO_DB_PORT', 5432),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_FINDERS = (
    ## Django defaults:
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    ## Other modules:
    'compressor.finders.CompressorFinder',
)

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]

## The directory on your filesystem where you want static files copied and served by YOUR WEB SERVER.
## When you run 'collectstatic', it copies them here.
## This is a production-only setting. It's not used in DEBUG mode.
## In DEBUG mode, files are served BY DJANGO from STATICFILES_DIRS var directory above.
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', '')

## The URL path from your app home, where static files will be served from (their URL base path)
## In DEBUG mode, files serve from your STATICFILES_DIRS directory.
## In production/non-DEBUG mode, files serve from your STATIC_ROOT filesystem path dir.
STATIC_URL = os.getenv('DJANGO_STATIC_URL', '/static-pagelab/')
MEDIA_URL = os.getenv('DJANGO_MEDIA_URL', '/media/')


## Compressor module settings.
## Compressor is default set to OPPOSITE of DEBUG. 
## To force compressor locally during debug, add "COMPRESS_ENABLED = True" var to your settings_local.py
COMPRESS_ROOT = os.path.join(BASE_DIR, "static/")
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter', 
    'compressor.filters.cssmin.rCSSMinFilter'
]

## Custom signin, signout, and post-signout page.
LOGIN_URL = '%s/report/signin/' % FORCE_SCRIPT_NAME
LOGOUT_URL = '%s/report/signout/' % FORCE_SCRIPT_NAME
LOGOUT_REDIRECT_URL = '%s/report/signedout/' % FORCE_SCRIPT_NAME


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


## Local settings override for ease, instead of/in addition to using ENV vars.
## Create a settings_local.py and override any vars above, even if they were set in your ENV.
try:
    from .settings_local import *
except ImportError:
    pass
    
