# Generated by Django 2.0 on 2018-10-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181026_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertimingmeasureaverage',
            options={'ordering': ['start_time']},
        ),
    ]
