# Generated by Django 2.0 on 2018-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20181026_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='user_timings_migrated',
            field=models.DateTimeField(null=True),
        ),
    ]
