# Generated by Django 2.0.8 on 2018-11-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_url_user_timings_migrated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=128)),
                ('val', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UrlFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UrlFilterPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(choices=[('protocol', 'protocol'), ('host', 'host'), ('hostname', 'hostname'), ('port', 'port'), ('pathname', 'pathname'), ('path_segment', 'path_segment'), ('search', 'search'), ('search_key', 'search_key'), ('hash', 'hash'), ('origin', 'origin')], max_length=16)),
                ('filter_key', models.CharField(blank=True, max_length=128, null=True)),
                ('filter_val', models.CharField(max_length=128)),
                ('url_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_filter_part_url_filter', to='report.UrlFilter')),
            ],
            options={
                'ordering': ['prop'],
            },
        ),
        migrations.CreateModel(
            name='UrlOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=64)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_description', models.TextField(blank=True, null=True)),
                ('owner_homepage', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['owner_name'],
            },
        ),
        migrations.CreateModel(
            name='UrlPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='url',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='host',
            field=models.CharField(default='https://ibm.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='hostname',
            field=models.CharField(default='https://ibm.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='origin',
            field=models.CharField(default='https://ibm.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='parsed_url',
            field=models.URLField(default='https://ibm.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='pathname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='port',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='protocol',
            field=models.CharField(default='https', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urlpath',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_path_url', to='report.Url'),
        ),
        migrations.AddField(
            model_name='searchkeyval',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_key_val_url', to='report.Url'),
        ),
        migrations.AddField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_owner_url', to='report.UrlOwner'),
        ),
    ]
