# Generated by Django 2.0.8 on 2018-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20181107_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='pathname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
