# Generated by Django 2.0.8 on 2018-11-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181107_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlfilterpart',
            name='filter_path_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='parsed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='protocol',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='urlfilter',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
