# Generated by Django 2.0.8 on 2018-11-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20181108_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='search_key_vals',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url_paths',
        ),
        migrations.AddField(
            model_name='searchkeyval',
            name='url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_key_val_url', to='report.Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlpath',
            name='url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='url_path_url', to='report.Url'),
            preserve_default=False,
        ),
    ]
