# Generated by Django 2.0.8 on 2018-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20181108_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlpath',
            options={'ordering': ['path']},
        ),
        migrations.AlterField(
            model_name='url',
            name='search_key_vals',
            field=models.ManyToManyField(blank=True, to='report.SearchKeyVal'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_paths',
            field=models.ManyToManyField(blank=True, to='report.UrlPath'),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='sequence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
