# Generated by Django 2.0.8 on 2018-11-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20181129_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimingmeasurename',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timing_measure_name_team', to='report.Team'),
        ),
    ]
