# Generated by Django 2.0.8 on 2018-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_usertimingmeasurename_team'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usertimingmeasureaverage',
            index=models.Index(fields=['created_date', 'url', 'name'], name='report_user_created_e48272_idx'),
        ),
        migrations.AddIndex(
            model_name='usertimingmeasure',
            index=models.Index(fields=['created_date', 'url', 'name'], name='report_user_created_9a13d5_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthouserun',
            index=models.Index(fields=['created_date'], name='report_ligh_created_86d861_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthouserun',
            index=models.Index(fields=['url'], name='report_ligh_url_id_7cba93_idx'),
        ),
        migrations.AddIndex(
            model_name='urlpath',
            index=models.Index(fields=['path', 'sequence'], name='report_urlp_path_94a9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['url'], name='report_url_url_d2ecf9_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthousedataraw',
            index=models.Index(fields=['created_date', 'lighthouse_run'], name='report_ligh_created_df2ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='urlkpiaverage',
            index=models.Index(fields=['created_date', 'url'], name='report_urlk_created_51bf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchkeyval',
            index=models.Index(fields=['key', 'val'], name='report_sear_key_8430fe_idx'),
        ),
        migrations.AddIndex(
            model_name='urlfilterpart',
            index=models.Index(fields=['prop', 'filter_key', 'filter_path_index', 'filter_val'], name='report_urlf_prop_e995d7_idx'),
        ),
        migrations.AddIndex(
            model_name='usertimingmeasurename',
            index=models.Index(fields=['created_date', 'name'], name='report_user_created_3ee64b_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthousedatausertiming',
            index=models.Index(fields=['created_date', 'lighthouse_run'], name='report_ligh_created_118b5d_idx'),
        ),
    ]
