# Generated by Django 2.0.8 on 2018-12-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20181130_1123'),
        ('report', '0012_auto_20181109_1225'),
    ]

    operations = [
    ]
