# Generated by Django 2.0.8 on 2018-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_merge_20181204_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlfilter',
            name='mode',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlfilter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
